---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kle
  name: kle
  namespace: demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kle
  strategy:
    rollingUpdate:
      maxUnavailable: 1
  template:
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app: kle
              namespaces:
                - demo
              topologyKey: kubernetes.io/hostname
      containers:
        - image: ghcr.io/yshngg/kle:0.1
          imagePullPolicy: Always
          name: kle
          command:
            - /bin/kle
            - "--leader-elect"
            - "--leader-elect-namespace=demo"
          resources:
            limits:
              cpu: 250m
              memory: 500Mi
            requests:
              cpu: 50m
              memory: 100Mi
          ports:
            - containerPort: 2190
              name: http
      serviceAccountName: kle
