---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kle
  namespace: demo
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kle
rules:
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kle
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kle
subjects:
  - kind: ServiceAccount
    name: kle
    namespace: demo
