---
apiVersion: v1
kind: Service
metadata:
  name: kle
  namespace: demo
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 2190
      protocol: TCP
      targetPort: http
      appProtocol: http
